# Generated by Django 3.2.4 on 2021-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210618_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='device_id',
            field=models.CharField(max_length=80, unique=True, verbose_name='Device Serial Number'),
        ),
    ]
